### ISSUE TITLE
Problem with sendFakeUplink

### ISSUE THREAD

**Issue by Bha91** [antoniobusrod/packet-forwarder#3]
Problem in usage part, I put all usage code mentioned in Readme file, than change gateway id, server url and gateway port, and run it, and get this error:

```
async sendFakeUplink() {
      ^^^^^^^^^^^^^^

SyntaxError: Unexpected identifier
```

**Comment by antoniobusrod** [comment]
Which version of node are you using?

**Comment by Bha91** [comment]
> Which version of node are you using?

v10.15.0

**Comment by antoniobusrod** [comment]
Hi @Bha91 , I'd like to ask you to clone this repo, install dependencies `npm i` and run the tests `npm t`.

**Comment by Bha91** [comment]
> Hi @Bha91 , I'd like to ask you to clone this repo, install dependencies `npm i` and run the tests `npm t`.

Thanks for replay.
`npm test` is ok, I am asked for usage part, that fail with error that I've mentioned.
