### ISSUE TITLE
String error when trying example code

### ISSUE THREAD

**Issue by andershedberg** [antoniobusrod/packet-forwarder#5]
Hi, first I don't understand node.js so I just installed Npm, did npm install packet-forwarder and tried the example in the readme.md file by doing a call to sendFakeUpling() . The result is this... Am I doing something wrong, or is the code wrong in some way? Oj. Ive tried it on windows 7 and windows 10. Same result. 
---

(node:16968) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Ar
ray-like Object. Received undefined
    at Function.from (buffer.js:331:9)
    at sanitizeBuffer (C:\code\dev-suite\node_modules\packet-forwarder\lib\index.js:11:17)
    at new PacketForwarder (C:\code\dev-suite\node_modules\packet-forwarder\lib\index.js:25:20)
    at sendFakeUplink (C:\code\dev-suite\lora-packet-gateway\cube02-lora-sensefarm-com.js:7:29)
    at Object.<anonymous> (C:\code\dev-suite\lora-packet-gateway\cube02-lora-sensefarm-com.js:13:1)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
(node:16968) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejec
ting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nod
ejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:16968) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process w
ith a non-zero exit code.

**Comment by andershedberg** [comment]
Fiddling around 

If the {} is removed from the constructor line 
``` 
constructor ( gateway, target, port, clientUdpPort ) {
``` 
and a resolve is inserted after the bytes = _bytes 
```
        bytes = _bytes
        resolve(bytes)
```
the code seems to run without node errors. Have not been able to test it yet against a server...

**Comment by antoniobusrod** [comment]
Hello @andershedberg , I would encourage to learn the basics of Node.js, before using `packet-forwarder` module. Moreover, a good knowledge of LoRaWAN protocol will help you as well.

I have updated the documentation, in particular, the usage example. If you want to run a similar script than in the usage example, you need to use a gateway and device registered in a Network Server. You can use [Loriot public Network Server](https://loriot.io/register.html).

**Comment by andershedberg** [comment]
Thanks. We have been running the Chirpstack server for a few years, and build an application for agriculture on top of it together with sensors, and I managed to use your code together with the "lora-packet" project to encode the payload as well. It will hopefully be possible to use it in our continuous integration tests in some way. And I will try to learn node.js, usually I just manage the software development but when people are on vacation I tend to do more fun stuff ;-) Just got this link this morning - https://docs.microsoft.com/en-gb/learn/paths/build-javascript-applications-nodejs/?fbclid=IwAR0UmZPsmSGJLnB9DCwFgtjiNiuDkBXoaF0KJsiZd79q12YOPqwDzgqvqMw
